### ISSUE TITLE
[Bug] torch.autograd.grad never ends, if `ChannelWiseTensorProduct` is used with specific configuration

### ISSUE THREAD

**Issue by YutackPark** [NVIDIA/cuEquivariance#33]
torch version: `2.4.0+cu121`
CUDA version: 12.3
cuEquivariance: `0.1.0`
, and `cuequivariance-ops-torch-cu12` is used

The program is not responding when one of `irreps_in` has a single multiplicity, and if grad is computed with respect to tensor of that single multiplicity irreps.

Minimal code to reproduce.

```python
  import cuequivariance as cue
  import cuequivariance_torch as cuet

  import torch

  print(torch.__version__)  # 2.4.0+cu121

  irreps_in1 = cue.Irreps('SO3', '128x0')  # works if not : 32, 64, 128
  irreps_in2 = cue.Irreps('SO3', '1x0+1x1+1x2')  #  works if multiplicity is > 1
  irreps_out = cue.Irreps('SO3', '128x0+128x1+128x2')

  tp = cuet.ChannelWiseTensorProduct(
      irreps_in1,
      irreps_in2,
      irreps_out,
      layout=cue.mul_ir,
      shared_weights=False,
      internal_weights=False,
      device='cuda'
  )

  x = torch.randn((10, tp.irreps_in1.dim), device='cuda')
  y = torch.randn((10, tp.irreps_in2.dim), device='cuda')
  w = torch.randn((10, tp.weight_numel), device='cuda')
  y.requires_grad = True

  zz = tp(x, y, w)

  grad = torch.autograd.grad(
      torch.sum(zz),
      [y],  # x, z fine
      create_graph=False,
      allow_unused=True
  )
  print(grad)  # program is not responding
```

It is a common configuration when one of the input is from the spherical harmonics. Using CPU instead of CUDA, or using the other multiplicity numbers (!= 32 | 64 | 128) for `irreps_in1` works without an error.

I'll check for `cuequivariance-ops-torch-cu11` can solve this issue.

**Comment by YutackPark** [comment]
Update: 
cu11 doesn' help. 
Increasing L of `irreps_in2` to 3 works (therefore MACE MP works).

**Comment by v0i0** [comment]
Thank you for the bug-report! I took a look, and it will be fixed with the next release of the kernel package.
