### ISSUE TITLE
How to call equivariant CUDA Kernels outside of Python?

### ISSUE THREAD

**Issue by adrhill** [NVIDIA/cuEquivariance#34]
First of all, thanks for writing equivariant CUDA Kernels. I have two questions regarding the package:
1. Am I correct in my assumption that the actual kernel implementations loaded by `cuequivariance-ops-*` packages are closed source?
2. Is there currently no way to call the kernels from other programming languages? I would be interested in writing bindings for Julia via [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl).

**Comment by v0i0** [comment]
Hi @adrhill,

Indeed, the kernels provided by cuequivariance-ops-* are closed source.
Currently, we only provide Python bindings, and utilizing them to bind to something else might be extremely difficult.

I guess for your use-case, a C-level API would be most helpful?
I will note this down as a feature request, and update you here if we decide to implement it.

For now, I'll close this as it is neither a bug nor committed for implementation.
