### ISSUE TITLE
Kernel wrapper in JAX ?

### ISSUE THREAD

**Issue by mitkotak** [NVIDIA/cuEquivariance#38]
Wondering whether there are plans to support kernel wrapper in [JAX as well ?](https://github.com/NVIDIA/cuEquivariance/blob/main/cuequivariance_jax/cuequivariance_jax/primitives/tensor_product.py#L226)

**Comment by mariogeiger** [comment]
We explored some ideas, we had a preliminary binding that was working but required the nightly version of JAX.
Lately the question was wether we just bind the same kernels as for torch (forward, backward and double backward) or if we develop something more generic that can handle any derivative.
