### ISSUE TITLE
Comparison/Improvements of `cuEquivariance` over `e3nn`

### ISSUE THREAD

**Issue by duydl** [NVIDIA/cuEquivariance#39]
Hi,  
Thank you for sharing this project! Could you provide a brief comparison or outline any improvements `cuEquivariance` offers over the established `e3nn` library? Specifically, I’m curious about performance, flexibility, and API design.  

Thanks for your time and work!

**Comment by hiranumn** [comment]
I am curious to hear about this as well.

**Comment by becca** [comment]
There a few notable differences between e3nn and cuEquivariance, namely around performance, flexibility and API design.
1. MACE with cuEquivariance have notable speedups, some of which we published in https://developer.nvidia.com/blog/accelerate-drug-and-material-discovery-with-new-math-library-nvidia-cuequivariance/. Additionally, MACE is now integrated with cuEquivariance (https://github.com/ACEsuit/mace/pull/704) 🎉 
2. e3nn is bound to a specific choice of SO3 irreps basis and data layout, in cuEquivariance you can specify your own [irreps basis](https://docs.nvidia.com/cuda/cuequivariance/api/generated/cuequivariance.Irrep.html) and tensor product by creating a [segmented tensor product](https://docs.nvidia.com/cuda/cuequivariance/tutorials/stp.html). 
3. We provide the new features mentioned above with an API that is very similar to that of e3nn.

Let us know if you have any other questions or feedback.

**Comment by LHJ1098826475** [comment]
Hi,

I'm glad you shared this technical blog ([https://developer.nvidia.com/blog/accelerate-drug-and-material-discovery-with-new-math-library-nvidia-cuequivariance/](https://developer.nvidia.com/blog/accelerate-drug-and-material-discovery-with-new-math-library-nvidia-cuequivariance/)).

I compared the performance of e3nn and cuEquivariance based on the test case provided in ([https://docs.nvidia.com/cuda/cuequivariance/tutorials/stp.html](https://docs.nvidia.com/cuda/cuequivariance/tutorials/stp.html)), and the results showed that cuEquivariance had no performance benefits. Is there any problem with my test script?

```shell
# cuEquivariance
import time
import itertools
import torch
import numpy as np

import cuequivariance as cue
import cuequivariance_torch as cuet
import cuequivariance.segmented_tensor_product as stp

device = torch.device("cuda:0")


# init irreps、descriptor
irreps_in = cue.Irreps("O3", "3000x0e")
irreps_out = cue.Irreps("O3", "3000x0e")
descriptor = stp.SegmentedTensorProduct.from_subscripts("uv,iu,iv")

# add segment
for mul, ir in irreps_in:
   descriptor.add_segment(1, (ir.dim, mul))
for mul, ir in irreps_out:
   descriptor.add_segment(2, (ir.dim, mul))

# add path
for (i1, (mul1, ir1)), (i2, (mul2, ir2)) in itertools.product(
   enumerate(irreps_in), enumerate(irreps_out)
):
   if ir1 == ir2:
      descriptor.add_path(None, i1, i2, c=1.0)

descriptor = descriptor.normalize_paths_for_operand(-1)

# compute
linear_torch = cuet.TensorProduct(descriptor, device=device)
w = torch.randn(descriptor.operands[0].size).to(device)
x1 = torch.randn((50000, irreps_in.dim)).to(device)
x2 = linear_torch(w, x1)  # warmup

# time statistics
loop = 10
torch.cuda.synchronize()
start = time.time()
for i in range(loop):
    x2 = linear_torch(w, x1)
torch.cuda.synchronize()
end = time.time()
print((end-start) / loop)

assert x2.shape == (50000, irreps_out.dim)
```

```shell
# e3nn
import time
import torch
from e3nn.o3 import Irreps, Linear

device = torch.device("cuda:0")

# init Linear
irreps_in = Irreps("3000x0e")
irreps_out = Irreps("3000x0e")
tp = Linear(irreps_in, irreps_out).to(device)

# compute
x1 = torch.randn((50000, irreps_in.dim)).to(device)
x2 = tp(x1)  # warmup

# time statistics
loop = 10
torch.cuda.synchronize()
start = time.time()
for i in range(loop):
    x2 = tp(x1)
torch.cuda.synchronize()
end = time.time()
print( (end-start) / loop)

assert x2.shape == (50000, irreps_out.dim)
```

![Image](https://github.com/user-attachments/assets/18c4bda8-c0cb-4fc5-a50e-e1520b70652b)


Besides the performance acceleration of cuEquivariance in the MACE and DiffDock models, have you conducted a performance comparison of TensorProduct interface? Can you provide test scripts at TensorProduct interface level?

Thanks
