### ISSUE TITLE
Doesn't work for Python 3.9 because of match statements

### ISSUE THREAD

**Issue by Ssbban** [NVIDIA/cuEquivariance#51]
Hi, I saw the Python version requirement on PyPI is >=3.9, but match statement is used on `cuequivariance/misc/linalg.py`. This seems to result in a syntax error on Python 3.9.

**Comment by mariogeiger** [comment]
We will change the requirements to 3.10, see [this PR](https://github.com/NVIDIA/cuEquivariance/pull/47)
